language: php

sudo: false

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.5
          services:
            - docker
        - php: 5.6
          services:
            - docker
        - php: 7.0
          services:
            - docker
        - php: 7.0
          env: COMPOSER_FLAGS='--prefer-lowest'
          services:
            - docker

before_install:
    - phpenv config-rm xdebug.ini
    - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script: ./tests/run.sh

notifications:
    email: false
